//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace abasilak.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\scagja\\Animations")]
        public string MeshLabLoadPath {
            get {
                return ((string)(this["MeshLabLoadPath"]));
            }
            set {
                this["MeshLabLoadPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\VCG\\MeshLab\\meshlabserver.exe")]
        public string MeshLabServerPath {
            get {
                return ((string)(this["MeshLabServerPath"]));
            }
            set {
                this["MeshLabServerPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\VCG\\MeshLab")]
        public string MeshLabExtensionsPath {
            get {
                return ((string)(this["MeshLabExtensionsPath"]));
            }
            set {
                this["MeshLabExtensionsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\scagja\\Models")]
        public string PoseSequencePath {
            get {
                return ((string)(this["PoseSequencePath"]));
            }
            set {
                this["PoseSequencePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\scagja\\Textures")]
        public string TexturePath {
            get {
                return ((string)(this["TexturePath"]));
            }
            set {
                this["TexturePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\scagja\\SMAs")]
        public string SMALoadPath {
            get {
                return ((string)(this["SMALoadPath"]));
            }
            set {
                this["SMALoadPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Andreas\\Desktop\\")]
        public string DesktopPath {
            get {
                return ((string)(this["DesktopPath"]));
            }
            set {
                this["DesktopPath"] = value;
            }
        }
    }
}
